// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4lmsceBcI8fV5plm05eKUrQRGA4uA9lY',
    appId: '1:882471268847:web:dd499e5ab6a62f7fc9c61a',
    messagingSenderId: '882471268847',
    projectId: 'raktarapp-24984',
    authDomain: 'raktarapp-24984.firebaseapp.com',
    storageBucket: 'raktarapp-24984.firebasestorage.app',
    measurementId: 'G-T898E4F5XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClJdKUH2wQUh_RbosqVBj4xanf2H0i5jw',
    appId: '1:882471268847:android:528692b460539e85c9c61a',
    messagingSenderId: '882471268847',
    projectId: 'raktarapp-24984',
    storageBucket: 'raktarapp-24984.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmR7-dyPvUKxDWSUdIgYbe9jvlh3PZfps',
    appId: '1:882471268847:ios:c7913d0ed44ba4eec9c61a',
    messagingSenderId: '882471268847',
    projectId: 'raktarapp-24984',
    storageBucket: 'raktarapp-24984.firebasestorage.app',
    iosBundleId: 'com.example.raktarkezelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmR7-dyPvUKxDWSUdIgYbe9jvlh3PZfps',
    appId: '1:882471268847:ios:c7913d0ed44ba4eec9c61a',
    messagingSenderId: '882471268847',
    projectId: 'raktarapp-24984',
    storageBucket: 'raktarapp-24984.firebasestorage.app',
    iosBundleId: 'com.example.raktarkezelo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4lmsceBcI8fV5plm05eKUrQRGA4uA9lY',
    appId: '1:882471268847:web:aa31ee3a683168b6c9c61a',
    messagingSenderId: '882471268847',
    projectId: 'raktarapp-24984',
    authDomain: 'raktarapp-24984.firebaseapp.com',
    storageBucket: 'raktarapp-24984.firebasestorage.app',
    measurementId: 'G-KSYW3T6VTS',
  );

}